config/routes.rb
FOR::Application.routes.draw do

  resources :users
  resources :meals

  root :to => 'home#index'

  match '/login' => 'session#new', :via => :get
  match '/logout' => 'session#destroy', :via => :get
  match '/session' => 'session#create', :via => :post

  match '/my_prefs', to: 'users#buyer_pref'

end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id               :integer          not null, primary key
#  meal_name        :string(255)
#  meal_price       :decimal(, )
#  meal_description :text
#  meal_photo       :string(255)
#  type_american    :boolean
#  type_asian       :boolean
#  type_mexican     :boolean
#  type_barbecue    :boolean
#  type_vegetarian  :boolean
#  type_snack       :boolean
#  type_hot_food    :boolean
#  type_soup        :boolean
#  type_dessert     :boolean
#  has_allergies    :boolean
#  user_id          :integer
#

class Meal < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                         :integer          not null, primary key
#  first_name                 :string(255)
#  last_name                  :string(255)
#  username                   :string(255)
#  email_address              :string(255)
#  password_digest            :string(255)
#  zip_code                   :string(255)
#  phone_number               :string(255)
#  gender                     :string(255)
#  birthday                   :string(255)
#  buyer_fresh_preference     :string(255)
#  buyer_distance_preference  :integer
#  likes_american             :boolean
#  likes_asian                :boolean
#  likes_mexican              :boolean
#  likes_barbecue             :boolean
#  likes_vegetarian           :boolean
#  likes_snack                :boolean
#  likes_hot_food             :boolean
#  likes_cold_food            :boolean
#  likes_soup                 :boolean
#  likes_dessert              :boolean
#  has_allergies              :boolean
#  is_seller                  :boolean
#  seller_distance_preference :integer
#  seller_delivery_preference :boolean
#  seller_pickup_preference   :boolean
#  created_at                 :datetime         not null
#  updated_at                 :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  has_secure_password
  has_many :meals

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable,

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email_address, :password, :password_confirmation, :remember_me, :zip_code, :phone_number, :gender, :birthday,
  # :buyer_fresh_preference, :buyer_distance_preference, :likes_american, :likes_asian, :likes_mexican, :likes_barbecue, :likes_vegetarian,
  # :likes_snack, :likes_hot_food, :likes_cold_food, :likes_soup, :likes_dessert, :has_allergies, :seller_distance_preference, :seller_delivery_preference,
  # :seller_pickup_preference

  # attr_accessible :title, :body

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user
  private

  def authenticate_user
    if session[:user_id]
        @auth = User.find(session[:user_id])
    else
        @auth = nil
    end
    rescue ActiveRecord::RecordNotFound
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(params[:meal])
    @auth.meals << @meal
    if @meal.save
        redirect_to @meal
    else
      render :new
    end
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def show
    @meal = Meal.find(params[:id])
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), :notice => "#{user.username} has logged in."
    else
      flash.now.alert = 'Login failed'
      render :new
    end
  end

  def destroy
      session[:user_id] = nil
      redirect_to login_path
      end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if @auth
      redirect_to dashboard_index_path
    else
    end
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_index_path(user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def login
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    redirect_to user
  end


  def buyer_pref
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def check_box_tag(name, value = "1", checked = false, options = {})
    html_options = { "type" => "checkbox", "name" => name, "id" => sanitize_to_id(name), "value" => value }.update(options.stringify_keys)
    html_options["checked"] = "checked" if checked
    tag :input, html_options
  end


  def meal_show_tag(user)
    if user.is_seller && user.meals
      a = "<h3>3Your Posted Meals:</h3>"
      b = []
      user.meals.each do |meal|
        b << meal.meal_name
      end
      puts "hello"
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h2>Welcome to FOR</h2>


<h3>this is the home page</h3><br/>


<%= link_to 'Register', new_user_path %><br/>

<%= link_to "Login", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FOR</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/meals/_mealnew.html.erb
<%= form_for (@meal) do |f| %>
  <% if @meal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved: </h2>
      <ul>
        <% @meals.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label "What is the meal name?" %>
    <%= f.text_field :meal_name %>
  </div>
  <div class="field">
    <%= f.label "Name your price" %>
    <%= f.text_field :meal_price %>
  </div>
  <div class="field">
    <%= f.label "Description" %>
    <%= f.text_field :meal_description %>
  </div>
  <div class="field">
    <%= f.label "Check all types that apply:" %>
    <%= f.check_box :type_american, :checked => false %><%= f.label "American" %>
    <%= f.check_box :type_asian, :checked => false %><%= f.label "Asian" %>
    <%= f.check_box :type_mexican, :checked => false %><% f.label "Mexican" %>
    <%= f.check_box :type_barbecue, :checked => false %><%= f.label "Barbecue" %>
    <%= f.check_box :type_vegetarian, :checked => false %><%= f.label "Vegetarian" %>
    <%= f.check_box :type_snack, :checked => false %><%= f.label "Snack" %>
    <%= f.check_box :type_hot_food, :checked => false %><%= f.label "Hot Food" %>
    <%= f.check_box :type_soup, :checked => false %><%= f.label "Soup" %>
    <%= f.check_box :type_dessert, :checked => false %><%= f.label "Dessert" %>
    <%= f.check_box :has_allergies, :checked => false %><%= f.label "Contains allergies" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Meals#edit</h1>

<p>Find me in app/views/meals/edit.html.erb</p>



<h3>This is where meals that were posted for sale are edited</h3>

app/views/meals/index.html.erb
<h1>Meals#index</h1>


<h3>This is an index of all meals posted</h3>

<p>Find me in app/views/meals/index.html.erb</p>

app/views/meals/new.html.erb
<h1>Meals#new</h1>
<p>Find me in app/views/meals/new.html.erb</p>

<h3>Post a Meal</h3>

<%= render 'mealnew' %>

app/views/meals/show.html.erb
<%= @meal.meal_name %>

<h1>Meals#show</h1>


<h3>This is the show page of a particular posted meal</h3>
<p>Find me in app/views/meals/show.html.erb</p>

app/views/session/new.html.erb
<% content_for :name, "home" %>

<h1 class="welcome twelve columns">Welcome to <span id="home-title">FOR</span></h1>

<div class="row" id="home-container">
  <div class="six columns">
    <div class="panel">
      <h2>
        Login
      </h2>
      <%= form_tag '/session' do %>
        <%= label_tag 'Username' %>
        <%= text_field_tag 'username' %>
        <%= label_tag 'Password' %>
        <%= password_field_tag 'password' %>
        <%= submit_tag 'Login' %>
      <% end %>
    </div>
  </div>
  <div class="six columns">
    <div class="panel callout radius">
      <h2>
        <%= link_to "Register", new_user_path %>
      </h2>
    </div>
  </div>
</div>

app/views/users/_buyerprofile.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label "What is your freshness preference?" %>
    <%= f.check_box :buyer_fresh_preference, :checked => true %><%= f.label "Same Day" %>
    <%= f.check_box :buyer_fresh_preference, :checked => false %><%= f.label "1-Day" %>
  </div>
  <div class="field">
    <%= f.label :buyer_distance_preference %>
    <%= f.text_field :buyer_distance_preference %>
  </div>

  <div class="field">
    <%= f.label "Do you like American?" %>
    <%= f.radio_button :likes_american, true %><%= f.label :likes_american, "Yes" %>
    <%= f.radio_button :likes_american, false %><%= f.label :likes_american, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Asian?" %>
    <%= f.radio_button :likes_asian, true %><%= f.label :likes_asian, "Yes" %>
    <%= f.radio_button :likes_asian, false %><%= f.label :likes_asian, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Mexican?" %>
    <%= f.radio_button :likes_mexican, true %><%= f.label :likes_mexican, "Yes" %>
    <%= f.radio_button :likes_mexican, false %><%= f.label :likes_mexican, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Barbecue?" %>
    <%= f.radio_button :likes_barbecue, true %><%= f.label :likes_barbecue, "Yes" %>
    <%= f.radio_button :likes_barbecue, false %><%= f.label :likes_barbecue, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Vegetarian?" %>
    <%= f.radio_button :likes_vegetarian, true %><%= f.label :likes_vegetarian, "Yes" %>
    <%= f.radio_button :likes_vegetarian, false %><%= f.label :likes_vegetarian, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Snacks?" %>
    <%= f.radio_button :likes_snack, true %><%= f.label :likes_snack, "Yes" %>
    <%= f.radio_button :likes_snack, false %><%= f.label :likes_snack, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Hot Food?" %>
    <%= f.radio_button :likes_hot_food, true %><%= f.label :likes_hot_food, "Yes" %>
    <%= f.radio_button :likes_hot_food, false %><%= f.label :likes_hot_food, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Cold Food?" %>
    <%= f.radio_button :likes_cold_food, true %><%= f.label :likes_cold_food, "Yes" %>
    <%= f.radio_button :likes_cold_food, false %><%= f.label :likes_cold_food, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Soup?" %>
    <%= f.radio_button :likes_soup, true %><%= f.label :likes_soup, "Yes" %>
    <%= f.radio_button :likes_soup, false %><%= f.label :likes_soup, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you like Dessert?" %>
    <%= f.radio_button :likes_dessert, true %><%= f.label :likes_dessert, "Yes" %>
    <%= f.radio_button :likes_dessert, false %><%= f.label :likes_dessert, "No" %>
  </div>
  <div class="field">
    <%= f.label "Do you have any allergies?" %>
    <%= f.radio_button :has_allergies, true %><%= f.label :has_allergies, "Yes" %>
    <%= f.radio_button :has_allergies, false %><%= f.label :has_allergies, "No" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/users/_formedit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.text_field :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_formnew.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email_address %>
    <%= f.text_field :email_address %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.text_field :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_sellerprofile.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: </h2>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :seller_distance_preference %>
    <%= f.text_field :seller_distance_preference %>
  </div>
  <div class="field">
    <%= f.label "Do you deliver?" %>
    <%= f.radio_button :seller_delivery_preference, true %><%= f.label :seller_delivery_preference, "Yes" %>
    <%= f.radio_button :seller_delivery_preference, false %><%= f.label :seller_delivery_preference, "No" %>
  </div>
  <div class="field">
    <%= f.label "Can I pickup my meal?" %>
    <%= f.radio_button :seller_pickup_preference, true %><%= f.label :seller_pickup_preference, "Yes" %>
    <%= f.radio_button :seller_pickup_preference, false %><%= f.label :seller_pickup_preference, "No" %>
    <%= f.hidden_field :is_seller, :value => true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/users/buyer_pref.html.erb
Buyer prefs

<%= form_for @user do |f| %>
<%= f.label :likes_asian, "Asian Food" %>
<%= f.text_field :likes_asian %>
<%= f.label :likes_mexican, "Mexican Food" %>
<%= f.text_field :likes_mexican %>
<%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<p>Find me in app/views/users/edit.html.erb</p>
<h1>Edit Profile</h1>

<%= render 'formedit' %>


<h3>Please complete your buyer profile</h3>
<div id="buyer_profile"><%= render 'buyerprofile' %>


<h3>Do you want to be a seller?</h3><button id="show">Yes</button><br/>
<div id="seller_profile"><%= render 'sellerprofile' %></div>

app/views/users/index.html.erb
<p>Find me in app/views/users/index.html.erb</p>

<h1>The current list of users are:</h1>

<h1><% @users.each do |user| %></h1>

<p><%= user.username %></p>
<td><%= link_to 'Show', user %></td>
<td><%= link_to 'Edit', edit_user_path(user) %></td>
<td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'}%></td>
<% end %>

<br/>
<br/>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Hey welcome to FOR</h1>

<h3>Create a New User</h3>


<%= render 'formnew' %>



<p>Find me in app/views/users/new.html.erb</p>


<%= link_to 'Login', login_path %>

app/views/users/show.html.erb
<%= link_to "logout", '/logout' %>

<% if @auth %>
  <div><h2>Welcome <%= @auth.first_name %></h2></div>
  <br>
<% end %>

<h1>Your username is: <%= @user.username %></h1>

<p>Find me in app/views/users/show.html.erb</p>


<%= link_to "Edit", edit_user_path %>
<%#= link_to "My Prefs", my_prefs_path %>
<%= link_to "Create New User", new_user_path %>
<%= link_to "Back to Index", users_path %><br/>

<% if @user.is_seller %>
    <%= link_to "Post a Meal", new_meal_path %>
<% end %>


<%= meal_show_tag(@user) %>


<% if @user.is_seller && @user.meals %>
  <h3>1Your Posted Meals:</h3>
  <% @user.meals.each do |meal| %>
  <%= meal.meal_name %><br/>
  <% end %>
<% end %>


<!-- <h3>2Your Posted Meals:<%# @user.meals.each do |meal| %></h3> -->
<!-- <%#= meal.meal_name %><br/> -->
<%# end %>